export const countries = [
    { code: 'ARG', name: 'Argentina' },
    { code: 'BOL', name: 'Bolivia' },
    { code: 'BRA', name: 'Brasil' },
    { code: 'CHL', name: 'Chile' },
    { code: 'COL', name: 'Colombia' },
    { code: 'CRI', name: 'Costa Rica' },
    { code: 'CUB', name: 'Cuba' },
    { code: 'ECU', name: 'Ecuador' },
    { code: 'SLV', name: 'El Salvador' },
    { code: 'GTM', name: 'Guatemala' },
    { code: 'HND', name: 'Honduras' },
    { code: 'JAM', name: 'Jamaica' },
    { code: 'MEX', name: 'México' },
    { code: 'NIC', name: 'Nicaragua' },
    { code: 'PAN', name: 'Panamá' },
    { code: 'PRY', name: 'Paraguay' },
    { code: 'PER', name: 'Perú' },
    { code: 'PRI', name: 'Puerto Rico' },
    { code: 'DOM', name: 'República Dominicana' },
    { code: 'TTO', name: 'Trinidad y Tobago' },
    { code: 'URY', name: 'Uruguay' },
    { code: 'VEN', name: 'Venezuela' }
]
